name: Skoice
version: ${project.parent.version}
main: net.clementraynaud.skoice.spigot.SkoicePluginSpigot
api-version: 1.13
authors: [ carlodrift, Lucas_Cdry ]
description: Proximity Voice Chat in Minecraft using Discord
website: ${project.url}
softdepend: [ DiscordSRV, EssentialsDiscordLink ]

commands:
  skoice:
    usage: /skoice
    description: The command to use Skoice.

permissions:
  skoice.manage:
    default: op
